{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubenav.rbacName" . }}
  labels:
    {{- include "kubenav.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      {{- if eq .Values.rbac.role "viewer" }}
      - 'get'
      - 'watch'
      - 'list'
      {{- else }}
      - '*'
      {{- end }}
  - nonResourceURLs:
      - '*'
    verbs:
      {{- if eq .Values.rbac.role "viewer" }}
      - 'get'
      - 'watch'
      - 'list'
      {{- else }}
      - '*'
      {{- end }}
{{- end -}}
