apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubenav.fullname" . }}
  labels:
    {{- include "kubenav.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubenav.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubenav.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kubenav.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if eq .Values.deployment.mode "kubeconfig" }}
            - --kubeconfig=/kubenav/kubeconfig/kubeconfig
            {{- else }}
            - --incluster
            {{- end }}
            {{- if .Values.plugins.prometheus.enabled }}
            - --plugin.prometheus.enabled
            - --plugin.prometheus.address={{ .Values.plugins.prometheus.address }}
            {{- end }}
          ports:
            - name: http
              containerPort: 14122
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if eq .Values.deployment.mode "kubeconfig" }}
          volumeMounts:
            - name: kubeconfig
              mountPath: '/kubenav/kubeconfig'
              readOnly: true
          {{- end }}
      {{- if eq .Values.deployment.mode "kubeconfig" }}
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
