{{- if eq .Values.deployment.mode "kubeconfig" -}}
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig
  labels:
    {{- include "kubenav.labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.deployment.kubeconfig | quote }}
{{- end -}}
