apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubenav.fullname" . }}-plugins
  labels:
    {{- include "kubenav.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (ne .Values.plugins.prometheus.username "") (ne .Values.plugins.prometheus.password "") }}
  KUBENAV_PROMETHEUS_USERNAME: {{ .Values.plugins.prometheus.username | b64enc }}
  KUBENAV_PROMETHEUS_PASSWORD: {{ .Values.plugins.prometheus.password | b64enc }}
  {{- end }}
  {{- if and (ne .Values.plugins.elasticsearch.username "") (ne .Values.plugins.elasticsearch.password "") }}
  KUBENAV_ELASTICSEARCH_USERNAME: {{ .Values.plugins.elasticsearch.username | b64enc }}
  KUBENAV_ELASTICSEARCH_PASSWORD: {{ .Values.plugins.elasticsearch.password | b64enc }}
  {{- end }}
  {{- if and (ne .Values.plugins.jaeger.username "") (ne .Values.plugins.jaeger.password "") }}
  KUBENAV_JAEGER_USERNAME: {{ .Values.plugins.jaeger.username | b64enc }}
  KUBENAV_JAEGER_PASSWORD: {{ .Values.plugins.jaeger.password | b64enc }}
  {{- end }}
